version: "3.9"
    
services:

  superapp:
    hostname: srv-miapp
    container_name: contenedor 
    # image: registrycicd:8085/${JOB_NAME}:latest
    image: registrycicd:8085/app-node-jenkins-nexus:latest

    ports: 
      - 80:3000 
    restart: always

  